### ISSUE TITLE
Download as PDF not working in localhost

### ISSUE THREAD

**Issue by adisadit** [hotosm/pdc-documentation#11]
Currently, download as pdf button is not working when I tried to build the site in my computer. Are there any requirements beside install Hugo in order to run build pdf in my computer?

or

Is it possible to create a stagging site for develop branch? Because I personally think that I prefer to fix the issue in develop branch before I merge it with the master branch.

Thank you so much!

**Comment by russbiggs** [comment]
There are quite a few other requirements for a full local build namely:

* node.js
* python (preferably with a virtualenv)
* pandoc (preferable not a local install but running through docker or maybe docker via circleci tooling)

I can try to document the local build process but a lot of the installations are tricky and inconsistent across platforms.

Let me think on the staging site for a develop branch. Since we're using github pages it may be a bit complicated to split the site into two sections (staging and prod)  I'd like to make sure whatever method we use for that is well documented and also consistent for the other documentation sites

**Comment by adisadit** [comment]
That would be awesome! Thank you Russ.

For staging site, if that idea is complicated, I'm perfectly fine with local build for pdf generation.

**Comment by russbiggs** [comment]
I’ll put together some documentation on the full local build

**Comment by russbiggs** [comment]
@adisadit I have made some modifications that allow for a local Docker build, however there are some more big changes in how we'll need to organize photos. Maybe we can schedule a walk through this week

**Comment by adisadit** [comment]
So I need to set up the docker environment in my laptop in order to successfully run the local build?

Yes sure how about this Thursday or Friday? Do you available at that time?

**Comment by russbiggs** [comment]
correct. Before we go through the docker build, you'll want to move all the image file to the /static/images directory.  From there you can add additional directories if needed.  We need to store image this way to handle multi-languages for the PDF build. Once everything is moved over on a develop branch I can get the dockerfile and new scripts into the repo

**Comment by adisadit** [comment]
So, if the module name is "Metodologi Pengumpulan Data", then the images will look like this:

/static/images/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data

or

/static/images/indonesia/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data --> for Indonesian language

/static/images/english/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data --> for English language


Is that correct?

**Comment by russbiggs** [comment]
The folder structure would be:

/static/id/images/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data --> for Indonesian language

/static/en/images/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data --> for English language

Then you reference in the Markdown:
```md
[!my image](/images/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data/my-image.png)
```

**Comment by adisadit** [comment]
Okay I got it Russ! This week we will move all the images to the proper location and then, later on, we will start translating all the materials to English. Will let you know if we finished moving the images.

**Comment by adisadit** [comment]
hi russ,

All the images already in the proper location. Could you check my PR? Thanks
