### ISSUE TITLE
large image filesize

### ISSUE THREAD

**Issue by russbiggs** [hotosm/pdc-documentation#5]
I ran a quick bash search on image files and thought this might help with reducing PDF size.  This is the list of all images over 1MB in size

* **3684.14 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0818_tampilangab.png

* **2970.89 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0801_Tampilan_mbtiles.png

* **2864.63 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0412_josm_data_quality_12.png

* **2846.63 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/07-Pembuatan-Peta-Survey-dengan-QGIS/images/0711_Tampilan_peta_dengan_citra_satelit.png

* **2783.82 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0406_josm_data_quality_6.png

* **2759.08 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0403_josm_data_quality_3.png

* **2722.85 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0407_josm_data_quality_7.png

* **2691.18 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0402_josm_data_quality_2.png

* **2647.08 kB** - 	 ./pages/03-JOSM/05-Menambahkan-Data-OSM-Menggunakan-JOSM/images/0513_menambahkan_citra.png

* **2313.69 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0410_josm_data_quality_10.png

* **2198.69 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/01-Metodologi-Kerangka-Kerja-Pemetaan-OpenStreetMap/images/0104_peta_survey.png

* **2166.64 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0405_josm_data_quality_5.png

* **2126.01 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0409_josm_data_quality_9.png

* **2093.01 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0408_josm_data_quality_8.png

* **2034.99 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/10-Konversi-Data-Shapefile-ke-GeoJSON/images/1006_overpass_1.png

* **2004.91 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/02-Model-Data-OpenStreetMap/images/0202_wiki_map_feature.png

* **1926.64 kB** - 	 ./pages/08-OSM-Data-Integration-to-InAWARE/01-Integrasi-OSM-ke-InAWARE/images/0102_osm_to_inaware.png

* **1828.22 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0811_tampilan_mbtiles_qgis.png

* **1681.49 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0823_tampilanhasilmbtiles.png

* **1654.04 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/10-Konversi-Data-Shapefile-ke-GeoJSON/images/1010_overpass_5.png

* **1648.76 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0819_tampilanbatas.png

* **1637.2 kB** - 	 ./pages/08-OSM-Data-Integration-to-InAWARE/01-Integrasi-OSM-ke-InAWARE/images/0103_osm_to_inaware.png

* **1627.9 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/07-Pembuatan-Peta-Survey-dengan-QGIS/images/0716_Pengaturan_skala_peta.png

* **1474.65 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/07-Pembuatan-Peta-Survey-dengan-QGIS/images/0722_peta_hasil.png

* **1417.14 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/08-Pembuatan-MBTiles-untuk-OpenMapKit/images/0825_hasildiOMK.png

* **1364.38 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/09-Perhitungan-Kuantitas-Data-Menggunakan-Plugin-Group-Stats/images/0907_tampilanbatas.png

* **1337.56 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0417_josm_data_quality_17.png

* **1324.29 kB** - 	 ./pages/04-Data-Validation-and-Quality-Assurance/04-JOSM-Untuk-Perhitungan-Kualitas-Data/images/0415_josm_data_quality_15.png

* **1271.38 kB** - 	 ./pages/03-JOSM/05-Menambahkan-Data-OSM-Menggunakan-JOSM/images/0511_download_data_osm.png

* **1268.91 kB** - 	 ./pages/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data/images/0105_metode_pengumpulan_data.png

* **1268.71 kB** - 	 ./pages/02-HOT-Tasking-Manager/01-Membuat-dan-Mengelola-Tasking-Manager/images/0106_alat_pada_tahapan_pengaturan_kotak_kerja.png

* **1180.06 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/03-Membuat-Presets-OpenStreetMap/images/0304_presets_4.png

* **1178.33 kB** - 	 ./pages/02-HOT-Tasking-Manager/02-Penggunaan-Tasking-Manager/images/0226_Area_yang_terarsir_tidak_boleh_Anda_petakan.png

* **1176.09 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/02-Model-Data-OpenStreetMap/images/0208_halaman_tag_info.png

* **1136.31 kB** - 	 ./pages/01-OSM-Field-Surveyor-Guideliness/01-Metodologi-Pengumpulan-Data/images/0104_metode_pengumpulan_data.png

* **1074.8 kB** - 	 ./pages/06-OSM-Field-Survey-Manager-Guidelines/09-Perhitungan-Kuantitas-Data-Menggunakan-Plugin-Group-Stats/images/0906_tampilanlayer.png

**Comment by adisadit** [comment]
thank you for this Russ. I will look this today and resize the image that over 1mb
